stages:
  - deploy

deploy_production:
  stage: deploy
  # We use the shell executor, so this runs directly on the Rocky OS server.
  script:
    # docker compose will automatically build the images and recreate the containers if needed
    - docker compose up -d --build
    
    # Prune dangling images to prevent the 21GB disk from filling up over time
    - docker image prune -f
  only:
    - main
