variables:
  GIT_CLEAN_FLAGS: "-ffdx -e certbot/"

stages:
  - deploy

deploy_production:
  stage: deploy
  environment: production
  script:
    - |
      cat <<EOF > .env
      DOMAIN_NAME=$DOMAIN_NAME
      CERTBOT_EMAIL=$CERTBOT_EMAIL
      ENABLE_SSL=$ENABLE_SSL
      EOF
    - chmod +x ./init-letsencrypt.sh
    - ./init-letsencrypt.sh
    - docker compose up -d --build
    - docker system prune -af --filter "until=72h"
  tags:
    - tcp-scanner
  only:
    - production
